# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-10 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='html',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
